_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.2
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 10
learning_rate:
    value: 0.001
